require_relative '../tools/sentinel/lib/sentinel'

# Dummy-Loader für Suiten ohne sie auszuführen
module Sentinel
  def self.extract_rules
    suites = []
    # Alle .rb Dateien in test/ durchgehen
    Dir.glob("test/**/*.rb").each do |file|
      # Überspringe Dateien, die keine Sentinel-Tests sind
      next if File.basename(file) == "README.md"

      # Wir definieren define_suite um, um nur Daten zu sammeln
      # ...

      def self.define_suite(name, &block)
        suite_data = { name: name, description: "", checks: [] }
        extractor = Object.new
        extractor.instance_variable_set(:@data, suite_data)
        def extractor.description(text); @data[:description] = text; end
        def extractor.check(name, &block)
          check_data = { name: name, rule: "" }
          ctx = Object.new
          ctx.instance_variable_set(:@data, check_data)
          def ctx.rule(text); @data[:rule] = text; end
          def ctx.target(t = nil); end
          def ctx.condition(&b); end
          def ctx.on_fail(m); end
          def ctx.fix(f); end
          ctx.instance_eval(&block)
          @data[:checks] << check_data
        end
        extractor.instance_eval(&block)
        @suites_list << suite_data
      end

      def self.define_skill(name, &block)
        suite_data = { name: "Skill: #{name}", description: "", checks: [] }
        extractor = Object.new
        extractor.instance_variable_set(:@data, suite_data)
        def extractor.description(text); @data[:description] = text; end
        def extractor.check(name, &block)
          check_data = { name: name, rule: "" }
          ctx = Object.new
          ctx.instance_variable_set(:@data, check_data)
          def ctx.rule(text); @data[:rule] = text; end
          def ctx.target(t = nil); end
          def ctx.condition(&b); end
          def ctx.on_fail(m); end
          def ctx.fix(f); end
          ctx.instance_eval(&block)
          @data[:checks] << check_data
        end
        extractor.instance_eval(&block)
        @suites_list << suite_data
      end

      @suites_list ||= []
      load file
    end
    @suites_list
  end

  def self.generate_markdown
    suites = extract_rules
    output = "# Project Rules & Skills (Generated by Sentinel)\n\n"
    output << "Diese Regeln und Skills werden automatisch aus der Sentinel Test-Suite generiert. Sie dienen als direkte Arbeitsanweisung für Entwickler und KI-Agenten.\n\n"

    # Zuerst die Skills
    output << "## 🧠 Agent Skills\n"
    output << "Diese Rollen-Profile definieren spezifische Fähigkeiten und Vorgehensweisen.\n\n"

    suites.select { |s| s[:name].start_with?("Skill:") }.each do |suite|
      output << "### 🛡️ #{suite[:name].sub('Skill: ', '')}\n"
      output << "#{suite[:description]}\n\n"
      suite[:checks].each do |check|
        output << "- **#{check[:name]}**: #{check[:rule]}\n"
      end
      output << "\n"
    end

    # Dann die technischen Ebenen
    output << "## 🛠️ Technical Integrity & Workflow\n"

    suites.reject { |s| s[:name].start_with?("Skill:") }.each do |suite|
      output << "### #{suite[:name]}\n"
      output << "#{suite[:description]}\n\n"
      suite[:checks].each do |check|
        output << "- **#{check[:name]}**: #{check[:rule]}\n"
      end
      output << "\n"
    end

    File.write('PROJECT_RULES.md', output)
    puts "PROJECT_RULES.md wurde erfolgreich generiert."
    generate_cursorrules(suites)
  end

  def self.generate_cursorrules(suites)
    output = "# MDTutor AI Instructions (Generated by Sentinel)\n\n"
    output << "Du bist ein Experten-KI-Assistent für das MDTutor-Projekt. Deine Arbeit wird durch das Sentinel-Framework (test/*) überwacht.\n\n"

    output << "## 🧠 Deine Skills & Rollen\n"
    suites.select { |s| s[:name].start_with?("Skill:") }.each do |suite|
      name = suite[:name].sub('Skill: ', '')
      output << "### #{name}\n"
      output << "#{suite[:description]}\n"
      suite[:checks].each do |check|
        output << "- **#{check[:name]}**: #{check[:rule]}\n"
      end
      output << "\n"
    end

    output << "## ⚖️ Verpflichtender Workflow\n"
    suites.reject { |s| s[:name].start_with?("Skill:") }.each do |suite|
      output << "### #{suite[:name]}\n"
      suite[:checks].each do |check|
        output << "- **#{check[:name]}**: #{check[:rule]}\n"
      end
      output << "\n"
    end

    output << "## 🔧 Fehlerbehebung\n"
    output << "Wenn du unsicher bist oder Tests fehlschlagen, führe `pnpm run test:sentinel:agent` aus. "
    output << "Die Ausgabe liefert dir direkt ausführbare `bash`-Fixes.\n"

    File.write('.cursorrules', output)
    puts ".cursorrules wurde erfolgreich generiert."
  end
end

Sentinel.generate_markdown
